/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pki.certconverter;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hlrrabbi
 */
public class CertConverter extends javax.swing.JFrame {

    /**
     * On Instancie CertConverter
     */
    public CertConverter() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("logo_certconvert.png");
        this.setIconImage(icon);
        
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CertConverter");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocation(new java.awt.Point(500, 125));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 368));
        getContentPane().setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(".pem, .crt, .p7b, p7c en DER (.der, .cer)");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(10, 46, 295, 23);

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        jLabel1.setText("Choisir le type de conversion à effectuer :");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 301, 15);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(".der, .cer, .p7b, .p7c en PEM (.pem, , .crt, .key) ");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(10, 83, 353, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText(".pem, .cer, .crt, .der en PKCS#7 (.p7b, p7c)");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(10, 124, 322, 23);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText(".pem, .cer, .crt, .der + clé privée(.key, PKCS#8)  en PKCS#12 (.pfx, .p12)");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(10, 164, 522, 23);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("PKCS#12 (.pfx, .p12) en PEM (.pem, .cer, .crt, .key) ");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(10, 205, 380, 23);

        jButton1.setText("Suivant =>");
        jButton1.setToolTipText("Passez à la conversion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 260, 111, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("logo_certconvert_mini.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 230, 200, 80);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));

        jMenu1.setText("Fichier");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Aide");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
               
    // Action à executer lorsqu'on clique sur le bouton suivant de notre application
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Permet à la fenetre en cours de faire appel à d'autes
                
        //instanciation des differentes fenetres de notre application pour pouvoir les ouvrir à partir d'ici.
        AnyFormatToDer pemtoder = new AnyFormatToDer();
        AnyFormatToPem dertopem=new AnyFormatToPem();
        Pem_DerToPkcs7 pemtopkcs7 = new Pem_DerToPkcs7();
        PemToPkcs12 pemtopkcs12 = new PemToPkcs12();
        Pkcs12ToPem pkcs12topem =new Pkcs12ToPem();
        
        // Ajout des actions sur les radiobuttons chaque fois qu'on les selectionne
        jRadioButton1.setActionCommand("1");
        jRadioButton2.setActionCommand("2");
        jRadioButton3.setActionCommand("3");
        jRadioButton5.setActionCommand("4");
        jRadioButton6.setActionCommand("5");
        
        //Condition et boucle pour aller à la fenetre suivante en utilisatnt la valeur des radiobutton
        String cmd = buttonGroup1.getSelection().getActionCommand();
        switch(cmd){
            case "1" :
                pemtoder.setVisible(true);
            break;
            case "2" :
                dertopem.setVisible(true);
            break;
            case "3" :
                pemtopkcs7.setVisible(true);
            break;
            case "4" :
                pemtopkcs12.setVisible(true);
            break;
            case "5" :
                pkcs12topem.setVisible(true);
            break;
            
               
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CertConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CertConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CertConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CertConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertConverter().setVisible(true);
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
